updated the ssm related actions

diff --git a/.github/actions/Deploy-SSM-Artifact/action.yml b/.github/actions/Deploy-SSM-Artifact/action.yml
--- a/.github/actions/Deploy-SSM-Artifact/action.yml
+++ b/.github/actions/Deploy-SSM-Artifact/action.yml
@@ -11,16 +11,25 @@ inputs:
     required: false
   executionRequired:
     required: false
-    default: false
+    default: "False"
   ServiceLanguage:
     required: false
     default: "SpringBoot"
   environmentName:
     required: false
-    default: main
+    default: "main"
   envRegion:
     required: false
     default: "ap-south-1"
+  executionType:
+    required: false
+    default: "Script"
+  ServiceName:
+    required: false
+    default: ""
+  ServiceDefFile:
+    required: false
+    default: ""
 
 ### Secrets as inputs ###
   AWS_ACCESS_KEY_ID:
@@ -58,52 +67,6 @@ run:
       run: |
         curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
         sudo dpkg -i session-manager-plugin.deb
-
-    - name: Check for Deployment Key (one-time check)
-      shell: bash
-      run: |
-        COMMAND_ID=$(aws ssm send-command \
-          --instance-ids "${{ inputs.INSTANCE_ID }}" \
-          --document-name "AWS-RunShellScript" \
-          --parameters 'commands=[
-            "if [ ! -f /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy ]; then",
-            "  echo \"Deploy key not found. Please set up manually. by running [ssh-keygen -t ed25519 -C 'deployment-key' -f /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy] \"",
-            "  echo \"and then go to GitHub: Repository Settings → Deploy Keys → Add deploy key and add the key there\"",
-            "  exit 1",
-            "else",
-            "  eval `ssh-agent -s`",
-            "  ssh-add /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy",
-            "fi",
-          ]'\
-          --query 'Command.CommandId' \
-          --output text
-        )
-        aws ssm wait command-executed \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}"
-
-        STATUS=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'Status' \
-          --output text)
-        STATUS_OUTPUT=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'StandardOutputContent' \
-          --output text)
-        STATUS_DETAILS=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'StatusDetails' \
-          --output text)
-
-        if [ "$STATUS" != "Success" ]; then
-          echo "::error::Deploy key not configured on VM. Please run setup first."
-          echo "::error::StatusDetails - $STATUS_DETAILS"
-          echo "::error::StatusOutput - $STATUS_OUTPUT"
-          exit 1
-        fi
     
     - name: Configure SSH
       shell: bash
@@ -130,8 +93,9 @@ run:
       shell: bash
       run: |
           scp -r ./artifact/* ${{ inputs.INSTANCE_USER }}@${{ inputs.INSTANCE_ID }}:${{ inputs.deploymentFolder }}/
+    
     - name: SpringBoot Execution [If required]
-      if: inputs.executionRequired == 'True' && (inputs.ServiceLanguage == 'SpringBoot' || inputs.ServiceLanguage == 'Java')
+      if: inputs.executionRequired == 'True' && (inputs.ServiceLanguage == 'SpringBoot' || inputs.ServiceLanguage == 'Java') && inputs.executionType == "Command"
       shell: bash
       run: |
         COMMAND_ID=$(aws ssm send-command \
@@ -147,9 +111,33 @@ run:
           --query 'Command.CommandId' \
           --output text
         )
-        aws ssm wait command-executed \
+        if ! aws ssm wait command-executed \
           --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}"
+          --instance-id "${{ inputs.INSTANCE_ID }}"; then
+          echo "::error::Command execution timed out or failed while starting the SpringBoot application"
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text 2>/dev/null || echo "Unknown")
+          STATUS_OUTPUT=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StandardOutputContent' \
+            --output text)
+          STATUS_DETAILS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StatusDetails' \
+            --output text)
+
+          echo "::error::Command Status: $STATUS"
+          echo "::error::StatusDetails - $STATUS_DETAILS"
+          echo "::error::StatusOutput - $STATUS_OUTPUT"
+
+          exit 1
+        fi
 
         STATUS=$(aws ssm get-command-invocation \
           --command-id "$COMMAND_ID" \
@@ -168,7 +156,76 @@ run:
           --output text)
 
         if [ "$STATUS" != "Success" ]; then
-          echo "::error::Deploy key not configured on VM. Please run setup first."
+          echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
+          echo "::error::StatusDetails - $STATUS_DETAILS"
+          echo "::error::StatusOutput - $STATUS_OUTPUT"
+          exit 1
+        fi
+
+    - name: Restarting Service on VM [AWS version]
+      if: inputs.executionRequired == 'True' && inputs.executionType == 'ServiceRestart'        
+      shell: bash
+      run: |
+        COMMAND_ID=$(aws ssm send-command \
+          --document-name "AWS-RunShellScript" \
+          --instance-ids "${{ inputs.INSTANCE_ID }}" \
+          --parameters 'commands=[
+            "cd ${{ inputs.deploymentFolder }}",
+            "sudo cp ./${{ inputs.ServiceDefFile }} /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+            "sudo chmod +x /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+            "sudo systemctl daemon-reload",
+            "sudo systemctl enable ${{ inputs.ServiceName }}",
+            "sudo systemctl restart ${{ inputs.ServiceName }}"
+          ]' \
+          --query 'Command.CommandId' \
+          --output text
+        )
+        if ! aws ssm wait command-executed \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ inputs.INSTANCE_ID }}"; then
+          echo "::error::Command execution timed out or failed while starting the  SpringBoot application"
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text 2>/dev/null || echo "Unknown")
+          STATUS_OUTPUT=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StandardOutputContent' \
+            --output text)
+          STATUS_DETAILS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StatusDetails' \
+            --output text)
+
+          echo "::error::Command Status: $STATUS"
+          echo "::error::StatusDetails - $STATUS_DETAILS"
+          echo "::error::StatusOutput - $STATUS_OUTPUT"
+
+          exit 1
+        fi
+
+        STATUS=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ inputs.INSTANCE_ID }}" \
+          --query 'Status' \
+          --output text)
+        STATUS_OUTPUT=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ inputs.INSTANCE_ID }}" \
+          --query 'StandardOutputContent' \
+          --output text)
+        STATUS_DETAILS=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ inputs.INSTANCE_ID }}" \
+          --query 'StatusDetails' \
+          --output text)
+
+        if [ "$STATUS" != "Success" ]; then
+          echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
           echo "::error::StatusDetails - $STATUS_DETAILS"
           echo "::error::StatusOutput - $STATUS_OUTPUT"
           exit 1
diff --git a/.github/actions/Deploy-SSM-Repo/action.yml b/.github/actions/Deploy-SSM-Repo/action.yml
--- a/.github/actions/Deploy-SSM-Repo/action.yml
+++ b/.github/actions/Deploy-SSM-Repo/action.yml
@@ -10,8 +10,8 @@ inputs:
     type: string
   executionRequired:
     required: false
-    type: boolean
-    default: false
+    type: string
+    default: "False"
   ServiceLanguage:
     required: false
     type: string
@@ -24,6 +24,18 @@ inputs:
     required: false
     type: string
     default: "ap-south-1"
+  executionType:
+    required: false
+    type: string
+    default: "Script"
+  ServiceName:
+    required: false
+    type: string
+    default: ""
+  ServiceDefFile:
+    required: false
+    type: string
+    default: ""
 
 ### Secrets as inputs ###
   AWS_ACCESS_KEY_ID:
@@ -53,7 +65,8 @@ run:
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch
 
-      - name: Check AWS CLI version
+      - name: Check AWS CLI version        
+        shell: bash
         run: aws --version
 
       - name: Configure AWS credentials
@@ -65,15 +78,17 @@ run:
           output-credentials: true
 
       - name: Install AWS CLI Session Manager plugin
+        shell: bash
         run: |
           curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
           sudo dpkg -i session-manager-plugin.deb
 
-      - name: Check for Deployment Key (one-time check)
+      - name: Sync repo to VM [AWS version] #clone/sync repo in VM through SSM        
+        shell: bash
         run: |
           COMMAND_ID=$(aws ssm send-command \
-            --instance-ids "${{ inputs.INSTANCE_ID }}" \
             --document-name "AWS-RunShellScript" \
+            --instance-ids "${{ inputs.INSTANCE_ID }}" \
             --parameters 'commands=[
               "if [ ! -f /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy ]; then",
               "  echo \"Deploy key not found. Please set up manually. by running [ssh-keygen -t ed25519 -C 'deployment-key' -f /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy] \"",
@@ -82,49 +97,10 @@ run:
               "else",
               "  eval `ssh-agent -s`",
               "  ssh-add /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy",
-              "fi",
-            ]'\
-            --query 'Command.CommandId' \
-            --output text
-          )
-          aws ssm wait command-executed \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ inputs.INSTANCE_ID }}"
-          
-          STATUS=$(aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ inputs.INSTANCE_ID }}" \
-            --query 'Status' \
-            --output text)
-          STATUS_OUTPUT=$(aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ inputs.INSTANCE_ID }}" \
-            --query 'StandardOutputContent' \
-            --output text)
-          STATUS_DETAILS=$(aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ inputs.INSTANCE_ID }}" \
-            --query 'StatusDetails' \
-            --output text)
-            
-          if [ "$STATUS" != "Success" ]; then
-            echo "::error::Deploy key not configured on VM. Please run setup first."
-            echo "::error::StatusDetails - $STATUS_DETAILS"
-            echo "::error::StatusOutput - $STATUS_OUTPUT"
-            exit 1
-          fi
-
-      - name: Sync repo to VM [AWS version] #clone/sync repo in VM through SSM
-        run: |
-          COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --instance-ids "${{ inputs.INSTANCE_ID }}" \
-            --parameters 'commands=[
-              "eval `ssh-agent -s`",
-              "ssh-add /home/${{ inputs.INSTANCE_USER }}/.ssh/github_deploy",
-              "ssh-keyscan github.com >> /home/${{ inputs.INSTANCE_USER }}/.ssh/known_hosts",
+              "fi"
+              "ssh-keyscan github.com | sort > /tmp/gh_key && grep -qF \"$(cat /tmp/gh_key)\" /home/${{ inputs.INSTANCE_USER }}/.ssh/known_hosts || cat /tmp/gh_key >> /home/${{ inputs.INSTANCE_USER }}/.ssh/known_hosts",
               "if [ ! -d \"${{ inputs.deploymentFolder }}\" ]; then",
-              "  mkdir ${{ inputs.deploymentFolder }}",
+              "  mkdir ${{ inputs.deploymentFolder }} -p",
               "fi",
               "cd ${{ inputs.deploymentFolder }}",
               "REPO_NAME=$(echo \"${{ github.repository }}\" | awk -F/ '\''{print $2}'\'')",
@@ -135,7 +111,7 @@ run:
               " cd $REPO_NAME",
               " git fetch origin ${{ steps.extract_branch.outputs.branch }}",
               " git checkout -B ${{ steps.extract_branch.outputs.branch }} origin/${{ steps.extract_branch.outputs.branch }}",
-              "fi",
+              "fi"
             ]' \
             --query 'Command.CommandId' \
             --output text
@@ -143,9 +119,8 @@ run:
           if ! aws ssm wait command-executed \
             --command-id "$COMMAND_ID" \
             --instance-id "${{ inputs.INSTANCE_ID }}"; then
-            echo "::error::Command execution timed out or failed while syncing repo to server"
-            
-            # Try to get command status for debugging
+            echo "::error::Command execution timed out or failed while starting the SpringBoot application"
+
             STATUS=$(aws ssm get-command-invocation \
               --command-id "$COMMAND_ID" \
               --instance-id "${{ inputs.INSTANCE_ID }}" \
@@ -161,17 +136,40 @@ run:
               --instance-id "${{ inputs.INSTANCE_ID }}" \
               --query 'StatusDetails' \
               --output text)
-            
-            echo "::error:: Repo Sync Failed"
+
             echo "::error::Command Status: $STATUS"
             echo "::error::StatusDetails - $STATUS_DETAILS"
             echo "::error::StatusOutput - $STATUS_OUTPUT"
-            
+
+            exit 1
+          fi
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+          STATUS_OUTPUT=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StandardOutputContent' \
+            --output text)
+          STATUS_DETAILS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StatusDetails' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
             exit 1
           fi
           
       - name: Execute script on VM [AWS version]
-        if: inputs.executionRequired
+        if: inputs.executionRequired == 'True' && inputs.executionType == 'Script'        
+        shell: bash
         run: |
           COMMAND_ID=$(aws ssm send-command \
             --document-name "AWS-RunShellScript" \
@@ -189,9 +187,8 @@ run:
           if ! aws ssm wait command-executed \
             --command-id "$COMMAND_ID" \
             --instance-id "${{ inputs.INSTANCE_ID }}"; then
-            echo "::error::Command execution timed out or failed while executing deployment script"
-            
-            # Try to get command status for debugging
+            echo "::error::Command execution timed out or failed while starting the SpringBoot application"
+
             STATUS=$(aws ssm get-command-invocation \
               --command-id "$COMMAND_ID" \
               --instance-id "${{ inputs.INSTANCE_ID }}" \
@@ -207,11 +204,104 @@ run:
               --instance-id "${{ inputs.INSTANCE_ID }}" \
               --query 'StatusDetails' \
               --output text)
-            
-            echo "::error::Script Execution Failed"
+
             echo "::error::Command Status: $STATUS"
             echo "::error::StatusDetails - $STATUS_DETAILS"
             echo "::error::StatusOutput - $STATUS_OUTPUT"
-            
+
+            exit 1
+          fi
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+          STATUS_OUTPUT=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StandardOutputContent' \
+            --output text)
+          STATUS_DETAILS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StatusDetails' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
+            exit 1
+          fi
+
+      - name: Restarting Service on VM [AWS version]
+        if: inputs.executionRequired == 'True' && inputs.executionType == 'ServiceRestart'        
+        shell: bash
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --instance-ids "${{ inputs.INSTANCE_ID }}" \
+            --parameters 'commands=[
+              "cd ${{ inputs.deploymentFolder }}",
+              "REPO_NAME=$(echo \"${{ github.repository }}\" | awk -F/ '\''{print $2}'\'')",
+              "cd $REPO_NAME",
+              "sudo cp ./${{ inputs.ServiceDefFile }} /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+              "sudo chmod +x /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+              "sudo systemctl daemon-reload",
+              "sudo systemctl enable ${{ inputs.ServiceName }}",
+              "sudo systemctl restart ${{ inputs.ServiceName }}"
+            ]' \
+            --query 'Command.CommandId' \
+            --output text
+          )
+          if ! aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}"; then
+            echo "::error::Command execution timed out or failed while starting the SpringBoot application"
+
+            STATUS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'Status' \
+              --output text 2>/dev/null || echo "Unknown")
+            STATUS_OUTPUT=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'StandardOutputContent' \
+              --output text)
+            STATUS_DETAILS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'StatusDetails' \
+              --output text)
+
+            echo "::error::Command Status: $STATUS"
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
+
+            exit 1
+          fi
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+          STATUS_OUTPUT=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StandardOutputContent' \
+            --output text)
+          STATUS_DETAILS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}" \
+            --query 'StatusDetails' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
             exit 1
           fi
