updated service restart

diff --git a/.github/actions/Deploy-SSM-Artifact/action.yml b/.github/actions/Deploy-SSM-Artifact/action.yml
--- a/.github/actions/Deploy-SSM-Artifact/action.yml
+++ b/.github/actions/Deploy-SSM-Artifact/action.yml
@@ -162,34 +162,61 @@ runs:
           exit 1
         fi
 
-    - name: Restarting Service on VM [AWS version]
-      if: inputs.executionRequired == 'True' && inputs.executionType == 'ServiceRestart'        
-      shell: bash
-      run: |
-        COMMAND_ID=$(aws ssm send-command \
-          --document-name "AWS-RunShellScript" \
-          --instance-ids "${{ inputs.INSTANCE_ID }}" \
-          --parameters 'commands=[
-            "cd ${{ inputs.deploymentFolder }}",
-            "sudo cp ./${{ inputs.ServiceDefFile }} /etc/systemd/system/${{ inputs.ServiceDefFile }}",
-            "sudo chmod +x /etc/systemd/system/${{ inputs.ServiceDefFile }}",
-            "sudo systemctl daemon-reload",
-            "sudo systemctl enable ${{ inputs.ServiceName }}",
-            "sudo systemctl restart ${{ inputs.ServiceName }}"
-          ]' \
-          --query 'Command.CommandId' \
-          --output text
-        )
-        if ! aws ssm wait command-executed \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}"; then
-          echo "::error::Command execution timed out or failed while starting the  SpringBoot application"
+      - name: Restarting Service on VM [AWS version]
+        if: inputs.executionRequired == 'True' && inputs.executionType == 'ServiceRestart'        
+        shell: bash
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --instance-ids "${{ inputs.INSTANCE_ID }}" \
+            --parameters 'commands=[
+              "cd ${{ inputs.deploymentFolder }}",
+              "REPO_NAME=$(echo \"${{ github.repository }}\" | awk -F/ '\''{print $2}'\'')",
+              "cd $REPO_NAME",
+              "if [ -f \"./${{ inputs.ServiceDefFile }}\" ]; then",
+              " sudo cp ./${{ inputs.ServiceDefFile }} /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+              " sudo chmod +x /etc/systemd/system/${{ inputs.ServiceDefFile }}",
+              "fi",
+              "sudo systemctl daemon-reload",
+              "sudo systemctl enable ${{ inputs.ServiceName }}",
+              "sudo systemctl restart ${{ inputs.ServiceName }}"
+            ]' \
+            --query 'Command.CommandId' \
+            --output text
+          )
+          if ! aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ inputs.INSTANCE_ID }}"; then
+            echo "::error::Command execution timed out or failed while starting the SpringBoot application"
+
+            STATUS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'Status' \
+              --output text 2>/dev/null || echo "Unknown")
+            STATUS_OUTPUT=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'StandardOutputContent' \
+              --output text)
+            STATUS_DETAILS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ inputs.INSTANCE_ID }}" \
+              --query 'StatusDetails' \
+              --output text)
+
+            echo "::error::Command Status: $STATUS"
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
+
+            exit 1
+          fi
 
           STATUS=$(aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
             --instance-id "${{ inputs.INSTANCE_ID }}" \
             --query 'Status' \
-            --output text 2>/dev/null || echo "Unknown")
+            --output text)
           STATUS_OUTPUT=$(aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
             --instance-id "${{ inputs.INSTANCE_ID }}" \
@@ -201,32 +228,9 @@ runs:
             --query 'StatusDetails' \
             --output text)
 
-          echo "::error::Command Status: $STATUS"
-          echo "::error::StatusDetails - $STATUS_DETAILS"
-          echo "::error::StatusOutput - $STATUS_OUTPUT"
-
-          exit 1
-        fi
-
-        STATUS=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'Status' \
-          --output text)
-        STATUS_OUTPUT=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'StandardOutputContent' \
-          --output text)
-        STATUS_DETAILS=$(aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id "${{ inputs.INSTANCE_ID }}" \
-          --query 'StatusDetails' \
-          --output text)
-
-        if [ "$STATUS" != "Success" ]; then
-          echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
-          echo "::error::StatusDetails - $STATUS_DETAILS"
-          echo "::error::StatusOutput - $STATUS_OUTPUT"
-          exit 1
-        fi
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Error running: 'nohup java -jar ${{ inputs.deploymentFolder }}/*.jar > app.log 2>&1 &'."
+            echo "::error::StatusDetails - $STATUS_DETAILS"
+            echo "::error::StatusOutput - $STATUS_OUTPUT"
+            exit 1
+          fi
