updated VM Deployment design to git pull from VM rather than sync through action

diff --git a/.github/workflows/VM-Deployment.yml b/.github/workflows/VM-Deployment.yml
--- a/.github/workflows/VM-Deployment.yml
+++ b/.github/workflows/VM-Deployment.yml
@@ -32,6 +32,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Extract branch name
+        shell: bash
+        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
+        id: extract_branch
+
       - name: Check AWS CLI version
         if: inputs.envType == 'AWS'
         run: aws --version
@@ -44,9 +49,6 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
           output-credentials: true
-        # permissions:
-        #   id-token: write   # This is required for requesting the JWT
-        #   contents: read 
 
       - name: Install AWS CLI Session Manager plugin
         if: inputs.envType == 'AWS'
@@ -54,49 +56,89 @@ jobs:
           curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
           sudo dpkg -i session-manager-plugin.deb
 
-      # - name: AWS VM Deploy
-      #   # if: ${{ inputs.executionRequired && inputs.envType == 'AWS' }}
-      #   run: |
-      #     rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx -e "ssh -o ProxyCommand='aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=22'" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:${{ inputs.deploymentFolder }}
-    
-      - name: Configure SSH
+      - name: Setup deploy key (one-time check)
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids "${{ secrets.INSTANCE_ID }}" \
+            --parameters 'commands=[
+              "if [ ! -f ~/.ssh/github_deploy ]; then",
+              "  echo \"Deploy key not found. Please set up manually. by running [ssh-keygen -t ed25519 -C 'deployment-key' -f ~/.ssh/github_deploy] \"",
+              "  echo \"and then go to GitHub: Repository Settings → Deploy Keys → Add deploy key and add the key there\"",
+              "  exit 1",
+              "fi"
+            ]')
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}"
+          
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Deploy key not configured on VM. Please run setup first."
+            exit 1
+          fi
+
+      - name: Sync repo to VM [AWS version] #clone/sync repo in VM through SSM
+        if: inputs.envType == 'AWS'
+        run: |
+          SCRIPT_COMMAND_ID=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --instance-ids "${{ secrets.INSTANCE_ID }}" \
+            --parameters 'commands=[
+              "git config --global credential.helper",
+              "if [ ! -d \"${{ inputs.deploymentFolder }}\" ]; then",
+              "  mkdir ${{ inputs.deploymentFolder }}",
+              "fi",
+              "cd ${{ inputs.deploymentFolder }}",
+              "REPO_NAME=$(echo \"${{ github.repository }}\" | awk -F/ '\''{print $2}'\'')",
+              "if [ ! -d \"$REPO_NAME\" ]; then ",
+              " git clone https://${{ github.token }}@github.com/${{ github.repository }}.git --single-branch --branch ${{ steps.extract_branch.outputs.branch }}",
+              " cd $REPO_NAME",
+              "else",
+              " cd $REPO_NAME",
+              " git pull",
+              "fi",
+              "git credential-cache exit"
+            ]' \
+            --query 'Command.CommandId' \
+            --output text
+          )
+          aws ssm wait command-executed \
+            --command-id "$SCRIPT_COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}"
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Some error in cloning the repo or pulling latest changes"
+            exit 1
+          fi
+
+      - name: Set up SSH Key
+        uses: webfactory/ssh-agent@v0.9.0
+        if: inputs.envType == 'On-Prem'
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Add Known Hosts
+        if: inputs.envType == 'On-Prem'
         run: |
           mkdir -p ~/.ssh
-          cat >> ~/.ssh/config <<EOF
-          Host ${{ secrets.SSH_HOSTNAME }}
-            StrictHostKeyChecking accept-new
-            UserKnownHostsFile ~/.ssh/known_hosts
-            ProxyCommand aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=22
-          EOF
-
-      - name: Deploy Folder to AWS VM
+          ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts
+      - name: VM Deploy
+        if: inputs.envType == 'On-Prem'
         run: |
-          rsync -avz --exclude '.git' \
-            --chown=github:www-data \
-            --chmod=Dg=rwx,Fg=rwx \
-            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:${{ inputs.deploymentFolder }}
-            
-      - name: Execute script on AWS VM
-        if: ${{ inputs.executionRequired }}
+          rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:${{ inputs.deploymentFolder }}
+
+      - name: Execute script on VM
+        if: inputs.executionRequired and inputs.envType == 'On-Prem'
         run: |
-          aws ssm start-session --document-name 'AWS-StartNonInteractiveCommand' --parameters '{"command": ["chmod +x ${{ inputs.deploymentFolder }}/${{ inputs.runScript }}"]}' --target ${{ secrets.SSH_HOSTNAME }}
-          aws ssm start-session --document-name 'AWS-StartNonInteractiveCommand' --parameters '{"command": ["/bin/bash ${{ inputs.deploymentFolder }}/${{ inputs.runScript }}"]}' --target ${{ secrets.SSH_HOSTNAME }}
-      # - name: Set up SSH Key
-      #   uses: webfactory/ssh-agent@v0.9.0
-      #   with:
-      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-      # - name: Add Known Hosts
-      #   run: |
-      #     mkdir -p ~/.ssh
-      #     ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts
-
-      # - name: VM Deploy
-      #   if: ${{ inputs.executionRequired && inputs.envType == 'AWS' }}
-      #   run: |
-      #     rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:${{ inputs.deploymentFolder }}
-
-      # - name: Execute script on VM
-      #   if: ${{ inputs.executionRequired }}
-      #   run: |
-      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "chmod +x ${{ inputs.deploymentFolder }}/${{ inputs.runScript }} && /bin/bash ${{ inputs.deploymentFolder }}/${{ inputs.runScript }}"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "chmod +x ${{ inputs.deploymentFolder }}/${{ inputs.runScript }} && /bin/bash ${{ inputs.deploymentFolder }}/${{ inputs.runScript }}"
