updated the script execution step for aws and some minor updates

diff --git a/.github/workflows/VM-Deployment.yml b/.github/workflows/VM-Deployment.yml
--- a/.github/workflows/VM-Deployment.yml
+++ b/.github/workflows/VM-Deployment.yml
@@ -22,6 +22,10 @@ on:
         required: false
         type: string
         default: "AWS"
+      envRegion:
+        required: false
+        type: string
+        default: "ap-south-1"
 
 jobs:
   deploy:
@@ -121,6 +125,37 @@ jobs:
             echo "::error::Some error in cloning the repo or pulling latest changes"
             exit 1
           fi
+          
+      - name: Execute script on VM [AWS version]
+        if: inputs.envType == 'AWS' && inputs.executionRequired
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --instance-ids "${{ secrets.INSTANCE_ID }}" \
+            --parameters 'commands=[
+              "cd ${{ inputs.deploymentFolder }}",
+              "REPO_NAME=$(echo \"${{ github.repository }}\" | awk -F/ '\''{print $2}'\'')",
+              "cd $REPO_NAME",
+              "chmod +x ${{ inputs.runScript }}",
+              "/bin/bash ${{ inputs.runScript }}"
+            ]' \
+            --query 'Command.CommandId' \
+            --output text
+          )
+          aws ssm wait command-executed \
+            --command-id "$SCRIPT_COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}"
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.INSTANCE_ID }}" \
+            --query 'Status' \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "::error::Some error script execution"
+            exit 1
+          fi
 
       - name: Set up SSH Key
         uses: webfactory/ssh-agent@v0.9.0
@@ -139,6 +174,6 @@ jobs:
           rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:${{ inputs.deploymentFolder }}
 
       - name: Execute script on VM
-        if: inputs.executionRequired and inputs.envType == 'On-Prem'
+        if: inputs.executionRequired && inputs.envType == 'On-Prem'
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "chmod +x ${{ inputs.deploymentFolder }}/${{ inputs.runScript }} && /bin/bash ${{ inputs.deploymentFolder }}/${{ inputs.runScript }}"
